"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!m-nfs&0k@a!a2&v&+7f#6fg846nei-j!%0hh&ksaxpav481#6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'cookie_app',
    'session_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Session engine (choose one)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Database-backed sessions
# SESSION_ENGINE = 'django.contrib.sessions.backends.cache'  # Cache-backed sessions
# SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'  # Cache + database-backed sessions
# SESSION_ENGINE = 'django.contrib.sessions.backends.file'  # File-based sessions
# SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'  # Cache + database-backed sessions

# Session cookie age in seconds (default: 1209600 seconds, or 2 weeks)
# SESSION_COOKIE_AGE = 200

# Session cookie path (default: '/')
# SESSION_COOKIE_PATH = '/home'

# Whether to use a secure (HTTPS-only) session cookie (default: False)
# SESSION_COOKIE_SECURE = True

# Whether to expire the session when the user closes their browser (default: False)
# SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# File path for file-based session storage
# SESSION_FILE_PATH = os.path.join(BASE_DIR / 'session-file')

# Session cache alias to use for cache-backed sessions
# SESSION_CACHE_ALIAS = 'default'

# Prefix to use for cache keys (default: 'django.contrib.sessions.cache')
# SESSION_CACHE_KEY_PREFIX = 'myapp'

# Session serializer (default: 'django.contrib.sessions.serializers.JSONSerializer')
# SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
